// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Basic: typeof import('./src/components/Basic.vue')['default']
    Button: typeof import('./src/components/Button.vue')['default']
    Demo: typeof import('./src/components/Demo.vue')['default']
    Handler: typeof import('./src/components/Handler.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    OptionBase: typeof import('./src/components/OptionBase.vue')['default']
    RawDisplay: typeof import('./src/components/rawDisplay.vue')['default']
    Small: typeof import('./src/components/Small.vue')['default']
    TriggerTry: typeof import('./src/components/TriggerTry.vue')['default']
  }
}

export {}
